### ISSUE TITLE
Equipo: Eliminar los botones y que se vean fotos como un carrusel

### ISSUE THREAD

**Issue by Miguel22hp** [Miguel22hp/Web-Catedra#79]
Esto es una propuesta, no definitiva.

**Comment by Javisantir** [comment]
Esto se puede hacer pero es bastante complicado, habría que rehacer todo el css de esta parte e intentar cambiarlo a bootstrap. Posiblemente así hagamos que todo sea más sencillo.

https://www.w3schools.com/bootstrap/bootstrap_carousel.asp
