### ISSUE TITLE
Eventos: Añadir tres eventos

### ISSUE THREAD

**Issue by Miguel22hp** [Miguel22hp/Web-Catedra#82]
Try IT! – 18-22 de marzo de 2024 

Make IT - 26 de junio – 7 de julio de 2024 

RootedCON – 9 -11 de marzo de 2024

**Comment by Javisantir** [comment]
La rooted es del 7-9. 

https://www.redseguridad.com/agenda/rootedcon-2024_20240112.html#:~:text=12%2F01%2F2024%20RootedCON%20se%20celebrar%C3%A1%20en%20Madrid%20entre%20los,y%20conocer%20las%20%C3%BAltimas%20novedades%20en%20la%20ciberseguridad.

**Comment by Javisantir** [comment]
Añadida RootedCon

**Comment by Javisantir** [comment]
Añadidos eventos del tryit

**Comment by Javisantir** [comment]
https://innova-tsn.fi.upm.es/
